# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
# Triggers the workflow on push or pull request events
on: [ push, pull_request, workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Windows 32 and 64 bits build
  windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    strategy:
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          git submodule -q update --init --recursive
          mkdir build
          
          cmake -S . -B build
          if ($lastexitcode -ne 0) { exit $lastexitcode }
          
          cmake --build build --target package --config RelWithDebInfo
          if ($lastexitcode -ne 0) { exit $lastexitcode }

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: "slirp-slip-server" # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: build/*.zip

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: 'build/*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
